"""
Django settings for your TOM project.

Originally generated by 'django-admin startproject' using Django 2.1.1.
Generated by ./manage.py tom_setup on Sept. 26, 2024, 9:46 a.m.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import logging.config
import os
import pkgutil
import ast
import tempfile

from dotenv import dotenv_values

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

secret = dotenv_values(os.path.join(BASE_DIR, 'env/.bhtom.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secret.get("SECRET_KEY", '')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['visata.astrouw.edu.pl', 'localhost', '127.0.0.1', '*']
CORS_REPLACE_HTTPS_REFERER      = False
HOST_SCHEME                     = "http://"
SECURE_PROXY_SSL_HEADER         = None
SECURE_SSL_REDIRECT             = False
SESSION_COOKIE_SECURE           = False
CSRF_COOKIE_SECURE              = False
SECURE_HSTS_SECONDS             = None
SECURE_HSTS_INCLUDE_SUBDOMAINS  = False
SECURE_FRAME_DENY               = False

# Application definition

TOM_NAME = 'bhtom3'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'django_tables2',
    'guardian',
    'tom_common',
    'django_comments',
    'bootstrap4',
    'crispy_bootstrap4',
    'crispy_forms',
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'django_gravatar',
    'django_htmx',
    'tom_targets',
    'tom_alerts',
    'tom_catalogs',
    'tom_dataservices',
    'tom_observations',
    'tom_dataproducts',
    'django_tasks',
    'django_tasks.backends.database',
    'custom_code',
    'tom_swift',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'tom_common.middleware.Raise403Middleware',
    'tom_common.middleware.ExternalServiceMiddleware',
    'tom_common.middleware.AuthStrategyMiddleware',
]

ROOT_URLCONF = 'bhtom3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'

WSGI_APPLICATION = 'bhtom3.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'OPTIONS': {
            # Required by django_tasks.backends.database on SQLite.
            'transaction_mode': 'EXCLUSIVE',
            'timeout': 30,
        },
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
)

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = False

USE_TZ = True

DATETIME_FORMAT = 'Y-m-d H:i:s'
DATE_FORMAT = 'Y-m-d'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, '_static')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'data')
MEDIA_URL = '/data/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        }
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'INFO'
        }
    }
}

# Caching
# https://docs.djangoproject.com/en/dev/topics/cache/#filesystem-caching

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': tempfile.gettempdir()
    }
}

# TOM Specific configuration
TARGET_TYPE = 'SIDEREAL'

# Set to the full path of a custom target model to extend the BaseTarget Model with custom fields.
TARGET_MODEL_CLASS = 'custom_code.models.BhtomTarget'

# Define MATCH_MANAGERS here. This is a dictionary that contains a dotted module path to the desired match manager
# for a given model.
# For example:
# MATCH_MANAGERS = {
#    "Target": "custom_code.match_managers.CustomTargetMatchManager"
# }
MATCH_MANAGERS = {}

FACILITIES = {
    'LCO': {
        'portal_url': 'https://observe.lco.global',
        'api_key': secret.get('LCO_API_KEY', ''),
    },
    'GEM': {
        'portal_url': {
            'GS': 'https://139.229.34.15:8443',
            'GN': 'https://128.171.88.221:8443',
        },
        'api_key': {
            'GS': '',
            'GN': '',
        },
        'user_email': '',
        'programs': {
            'GS-YYYYS-T-NNN': {
                'MM': 'Std: Some descriptive text',
                'NN': 'Rap: Some descriptive text'
            },
            'GN-YYYYS-T-NNN': {
                'QQ': 'Std: Some descriptive text',
                'PP': 'Rap: Some descriptive text',
            },
        },
    },
    'SWIFT': {
            'SWIFT_USERNAME': secret.get("SWIFT_USERNAME"),
            'SWIFT_SHARED_SECRET': secret.get("SWIFT_SHARED_SECRET"),
        },
    'LT': {
           'proposalIDs': ((secret.get("LT_PROPOSAL_ID"), secret.get("LT_PROPOSAL_TITLE")), ),
           'username': secret.get("LT_PROPOSAL_USER"),
           'password': secret.get("LT_PROPOSAL_PASS"),
           'LT_HOST': '161.72.57.3',
           'LT_PORT': '8080',
           'DEBUG': False,
    },
    'REM': {
           'proposalIDs': ((52055, "DDT,PI:Pawel Zielinski"),),
           'email': "pzielinski@umk.pl",
    },
    'SUHORA': {
           'proposalIDs': ((9999, "BHTOM-Lukasz Wyrzykowski"),), #coma is needed after first proposal!
           'email': "wyrzykow@gmail.com",
    },
    'BOLECINA': {
           'proposalIDs': ((999, "BHTOM-Lukasz Wyrzykowski"),), #coma is needed after first proposal!
           'email': "wyrzykow@gmail.com",
    },
    'LESEDI': {
           'proposalIDs': ((99, "BHTOM-Lukasz Wyrzykowski"),), #coma is needed after first proposal!
           'email': "wyrzykow@gmail.com",
    },

    }

# Define the valid data product types for your TOM.
# This is a dictionary of tuples to be used as ChoiceField options, with the first element being the type and the
# second being the display name.
# Be careful when removing items, as previously valid types will no
# longer be valid, and may cause issues unless the offending records are modified.

DATA_PRODUCT_TYPES = {
    'photometry': ('photometry', ' Photometry - SExtractor format'),
    'photometry_csv': ('photometry_csv', 'Photometry - CSV'),
    'fits_file': ('fits_file', 'FITS File'),
    'spectroscopy': ('spectroscopy', 'Spectroscopy'),
    # 'image_file': ('image_file', 'Image File')
}
CLASSIFICATION_TYPES = [
    ("Unknown", "Unknown"), ('Be-star outburst', 'Be-star outburst'),
    ('AGN', "Active Galactic Nucleus(AGN)"), ("BL Lac", "BL Lac"),
    ("CV", "Cataclysmic Variable(CV)"), ("CEPH", "Cepheid Variable(CEPH)"),
    ("EB", "Eclipsing Binary(EB)"),
    ("Galaxy", "Galaxy"), ("LPV", "Long Period Variable(LPV)"),
    ("LBV", "Luminous Blue Variable(LBV)"),
    ("M-dwarf flare", "M-dwarf flare"), ("Microlensing Event", "Microlensing Event"), ("Nova", "Nova"),
    ("Peculiar Supernova", "Peculiar Supernova"),
    ("QSO", "Quasar(QSO)"), ("RCrB", "R CrB Variable"), ("RR Lyrae Variable", "RR Lyrae Variable"),
    ("SSO", "Solar System Object(SSO)"),
    ("Star", "Star"), ("SN", "Supernova(SN)"), ("Supernova imposter", "Supernova imposter"),
    ("Symbiotic star", "Symbiotic star"),
    ("TDE", "Tidal Disruption Event(TDE)"), ("Variable star-other", "Variable star-other"),
    ("XRB", "X-Ray Binary(XRB)"),
    ("YSO", "Young Stellar Object(YSO)")]

DATA_PROCESSORS = {
    'photometry': 'tom_dataproducts.processors.photometry_processor.PhotometryProcessor',
    'spectroscopy': 'tom_dataproducts.processors.spectroscopy_processor.SpectroscopyProcessor',
}

TOM_FACILITY_CLASSES = [
    'tom_observations.facilities.lco.LCOFacility',
    'tom_observations.facilities.gemini.GEMFacility',
    'tom_observations.facilities.soar.SOARFacility',
    'tom_swift.swift.SwiftFacility',
#    'tom_lt.lt.LTFacility',
    'bhtom3.bhtom_observations.facilities.lt.LTFacility',    
    'bhtom3.bhtom_observations.facilities.rem.REM',    
    'bhtom3.bhtom_observations.facilities.suhora.SUHORA',    
    'bhtom3.bhtom_observations.facilities.bolecina.BOLECINA',
    'bhtom3.bhtom_observations.facilities.lesedi.LESEDI',    

]

TOM_ALERT_CLASSES = [
    'tom_alerts.brokers.alerce.ALeRCEBroker',
    #  'tom_alerts.brokers.antares.ANTARESBroker',
    'tom_alerts.brokers.gaia.GaiaBroker',
    'tom_alerts.brokers.lasair.LasairBroker',
    'tom_alerts.brokers.tns.TNSBroker',
    #  'tom_alerts.brokers.fink.FinkBroker',
]


def _discover_custom_harvesters():
    discovered = []
    package_name = 'custom_code.bhtom_catalogs.harvesters'
    package_path = os.path.join(BASE_DIR, 'custom_code', 'bhtom_catalogs', 'harvesters')
    if not os.path.isdir(package_path):
        return discovered

    for _, mod_short, _ in pkgutil.iter_modules([package_path]):
        if mod_short.startswith('_'):
            continue
        module_name = f'{package_name}.{mod_short}'
        file_path = os.path.join(package_path, f'{mod_short}.py')
        if not os.path.isfile(file_path):
            continue
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                tree = ast.parse(f.read(), filename=file_path)
        except Exception:
            continue
        for node in tree.body:
            if not isinstance(node, ast.ClassDef):
                continue
            base_names = []
            for base in node.bases:
                if isinstance(base, ast.Name):
                    base_names.append(base.id)
                elif isinstance(base, ast.Attribute):
                    base_names.append(base.attr)
            if 'AbstractHarvester' in base_names:
                discovered.append(f'{module_name}.{node.name}')
    return discovered


BROKERS = {
    'TNS': {
        # BHTOM_Bot TNS API
        'api_key': secret.get('TNS_API_KEY', ''),
        'user_agent': 'tns_marker{"tns_id":99624,"type": "bot", "name":"BHTOM_Bot"}',
        'bot_id':99624,
        'bot_name':"BHTOM_Bot"
    },
    'Lasair': {
        'api_key': '',
    }
}

_BASE_HARVESTER_CLASSES = [
    'custom_code.bhtom_catalogs.harvesters.simbad.SimbadHarvester',
    'tom_catalogs.harvesters.ned.NEDHarvester',
    'tom_catalogs.harvesters.jplhorizons.JPLHorizonsHarvester',
    'tom_catalogs.harvesters.tns.TNSHarvester',
]
_CORE_CUSTOM_HARVESTER_CLASSES = [
    'custom_code.bhtom_catalogs.harvesters.gaia_dr3.GaiaDR3Harvester',
    'custom_code.bhtom_catalogs.harvesters.lsst.LSSTHarvester',
    'custom_code.bhtom_catalogs.harvesters.gaia_alerts.GaiaAlertsHarvester',
]
_BOTTOM_CUSTOM_HARVESTER_CLASSES = [
    'custom_code.bhtom_catalogs.harvesters.crts.CRTSHarvester',
]
_extra_custom_harvesters = [
    h for h in _discover_custom_harvesters()
    if h not in _CORE_CUSTOM_HARVESTER_CLASSES and h not in _BOTTOM_CUSTOM_HARVESTER_CLASSES
]
TOM_HARVESTER_CLASSES = (
    _CORE_CUSTOM_HARVESTER_CLASSES
    + _extra_custom_harvesters
    + _BASE_HARVESTER_CLASSES
    + _BOTTOM_CUSTOM_HARVESTER_CLASSES
)

HARVESTERS = {
    'TNS': {
        # BHTOM_Bot TNS API
        'api_key': secret.get('TNS_API_KEY', ''),
        'user_agent': 'tns_marker{"tns_id":99624,"type": "bot", "name":"BHTOM_Bot"}',
        'bot_id':99624,
        'bot_name':"BHTOM_Bot"
    }
}

# Define extra target fields here. Types can be any of "number", "string", "boolean" or "datetime"
# See https://tomtoolkit.github.io/docs/target_fields for documentation on this feature
# For example:
# EXTRA_FIELDS = [
#     {'name': 'redshift', 'type': 'number'},
#     {'name': 'discoverer', 'type': 'string'},
#     {'name': 'eligible', 'type': 'boolean'},
#     {'name': 'discovery_date', 'type': 'datetime'}
# ]
EXTRA_FIELDS = []

# Authentication strategy can either be LOCKED (required login for all views)
# or READ_ONLY (read only access to views)
AUTH_STRATEGY = 'READ_ONLY'

# Row-level data permissions restrict users from viewing certain objects unless they are a member of the group to which
# the object belongs. Setting this value to True will allow all `ObservationRecord`, `DataProduct`, and `ReducedDatum`
# objects to be seen by everyone. Setting it to False will allow users to specify which groups can access
# `ObservationRecord`, `DataProduct`, and `ReducedDatum` objects.
TARGET_PERMISSIONS_ONLY = True

# URLs that should be allowed access even with AUTH_STRATEGY = LOCKED
# for example: OPEN_URLS = ['/', '/about']
OPEN_URLS = []

HOOKS = {
    'target_post_save': 'custom_code.hooks.target_post_save',
    'observation_change_state': 'tom_common.hooks.observation_change_state',
    'data_product_post_upload': 'tom_dataproducts.hooks.data_product_post_upload',
    'data_product_post_save': 'tom_dataproducts.hooks.data_product_post_save',
    'multiple_data_products_post_save': 'tom_dataproducts.hooks.multiple_data_products_post_save',
}

# If True, newly-created targets will trigger asynchronous DataService
# queries in the background via the custom target_post_save hook.
# By default, all installed DataServices are queried.
# Optional: set AUTO_QUERY_DATA_SERVICE_NAMES = ('GaiaDR3', 'LSST', 'GaiaAlerts')
# to explicitly limit which services run automatically.
AUTO_QUERY_DATA_SERVICES_ON_TARGET_CREATE = True

AUTO_THUMBNAILS = False

THUMBNAIL_MAX_SIZE = (0, 0)

THUMBNAIL_DEFAULT_SIZE = (200, 200)

HINTS_ENABLED = True
HINT_LEVEL = 20

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
    ],
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 1000
}

TASKS = {
    "default": {
        "BACKEND": "django_tasks.backends.database.DatabaseBackend"
    }
}

# Default Plotly theme setting, can set to any valid theme:
# 'plotly', 'plotly_white', 'plotly_dark', 'ggplot2', 'seaborn', 'simple_white', 'none'
PLOTLY_THEME = 'plotly_white'

try:
    from local_settings import * # noqa
except ImportError:
    pass

TOMEMAIL: str  = secret.get('TOMEMAIL')
TOMEMAILPASSWORD: str = secret.get('TOMEMAILPASSWORD')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = secret.get('EMAIL_HOST')
EMAIL_PORT = secret.get('EMAIL_PORT')
EMAIL_USE_TLS = secret.get('EMAIL_USE_TLS', True)
EMAIL_HOST_USER = TOMEMAIL
EMAIL_HOST_PASSWORD = TOMEMAILPASSWORD
