# Generated by Django 5.2.12 on 2026-03-28 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0002_geotarget'),
        ('tom_targets', '0030_alter_basetarget_slope'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhtomtarget',
            name='phot_classification_done',
            field=models.BooleanField(db_index=True, default=False, verbose_name='photometric classification done'),
        ),
        migrations.AddField(
            model_name='geotarget',
            name='intldes',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='geotarget',
            name='is_debris',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='geotarget',
            name='object_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='geotarget',
            name='source',
            field=models.CharField(blank=True, db_index=True, default='manual', max_length=32),
        ),
        migrations.CreateModel(
            name='TargetAliasInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, default='', max_length=100)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('target_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alias_info', to='tom_targets.targetname')),
            ],
            options={
                'verbose_name': 'target alias info',
                'verbose_name_plural': 'target alias info',
            },
        ),
    ]
