# Generated by Django 5.2.12 on 2026-04-14 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0003_bhtomtarget_phot_classification_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhtomtarget',
            name='parallax_error',
            field=models.FloatField(blank=True, help_text='Parallax uncertainty, in milliarcseconds.', null=True, verbose_name='parallax error'),
        ),
        migrations.AddField(
            model_name='bhtomtarget',
            name='pm_dec_error',
            field=models.FloatField(blank=True, help_text='Proper Motion Dec uncertainty, in milliarcsec/year.', null=True, verbose_name='proper motion Dec error'),
        ),
        migrations.AddField(
            model_name='bhtomtarget',
            name='pm_ra_error',
            field=models.FloatField(blank=True, help_text='Proper Motion RA uncertainty, in milliarcsec/year.', null=True, verbose_name='proper motion RA error'),
        ),
        migrations.AlterField(
            model_name='bhtomtarget',
            name='classification',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Be-star outburst', 'Be-star outburst'), ('AGN', 'Active Galactic Nucleus(AGN)'), ('BL Lac', 'BL Lac'), ('CV', 'Cataclysmic Variable(CV)'), ('CEPH', 'Cepheid Variable(CEPH)'), ('EB', 'Eclipsing Binary(EB)'), ('Galaxy', 'Galaxy'), ('LPV', 'Long Period Variable(LPV)'), ('LBV', 'Luminous Blue Variable(LBV)'), ('M-dwarf flare', 'M-dwarf flare'), ('Microlensing Event', 'Microlensing Event'), ('Nova', 'Nova'), ('Peculiar Supernova', 'Peculiar Supernova'), ('Planetary Transit', 'Planetary Transit'), ('QSO', 'Quasar(QSO)'), ('RCrB', 'R CrB Variable'), ('RR Lyrae Variable', 'RR Lyrae Variable'), ('SSO', 'Solar System Object(SSO)'), ('Star', 'Star'), ('SN', 'Supernova(SN)'), ('Supernova imposter', 'Supernova imposter'), ('Symbiotic star', 'Symbiotic star'), ('TDE', 'Tidal Disruption Event(TDE)'), ('Variable star-other', 'Variable star-other'), ('XRB', 'X-Ray Binary(XRB)'), ('YSO', 'Young Stellar Object(YSO)')], db_index=True, help_text='Classification of the object (e.g. variable star, microlensing event)', max_length=50, null=True, verbose_name='classification'),
        ),
        migrations.CreateModel(
            name='TransitEphemeris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, default='', max_length=100)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('planet_name', models.CharField(blank=True, default='', max_length=100)),
                ('host_name', models.CharField(blank=True, default='', max_length=100)),
                ('priority', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('current_oc_min', models.FloatField(blank=True, null=True)),
                ('t0_bjd_tdb', models.FloatField(blank=True, null=True)),
                ('t0_unc', models.FloatField(blank=True, null=True)),
                ('period_days', models.FloatField(blank=True, null=True)),
                ('period_unc', models.FloatField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('depth_r_mmag', models.FloatField(blank=True, null=True)),
                ('v_mag', models.FloatField(blank=True, null=True)),
                ('r_mag', models.FloatField(blank=True, null=True)),
                ('gaia_g_mag', models.FloatField(blank=True, null=True)),
                ('min_telescope_inches', models.FloatField(blank=True, null=True)),
                ('total_observations', models.PositiveIntegerField(blank=True, null=True)),
                ('recent_observations', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transit_ephemeris', to='custom_code.bhtomtarget')),
            ],
            options={
                'verbose_name': 'transit ephemeris',
                'verbose_name_plural': 'transit ephemerides',
            },
        ),
    ]
