# Generated by Django 5.2.12 on 2026-03-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0003_alter_geotarget_id'),
        ('custom_code', '0003_geotarget_metadata'),
    ]

    operations = [
    ]
