# Generated by Django 5.2.12 on 2026-03-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0004_merge_0003_alter_geotarget_id_0003_geotarget_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhtomtarget',
            name='phot_classification_done',
            field=models.BooleanField(db_index=True, default=False, verbose_name='photometric classification done'),
        ),
    ]
