# Generated by Django 5.2.12 on 2026-04-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0004_bhtomtarget_parallax_error_bhtomtarget_pm_dec_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhtomtarget',
            name='gaia_variability_type',
            field=models.CharField(blank=True, help_text='Gaia DR3 variability class from vari_classifier_result.best_class_name.', max_length=64, null=True, verbose_name='Gaia variability type'),
        ),
    ]
