# Generated by Django 5.2.12 on 2026-03-28 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0030_alter_basetarget_slope'),
        ('custom_code', '0005_bhtomtarget_phot_classification_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetAliasInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('target_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alias_info', to='tom_targets.targetname')),
            ],
            options={
                'verbose_name': 'target alias info',
                'verbose_name_plural': 'target alias info',
            },
        ),
    ]
