# Generated by Django 5.2.12 on 2026-05-26 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0005_bhtomtarget_gaia_variability_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('account_schema', models.JSONField(blank=True, default=dict)),
                ('proposal_schema', models.JSONField(blank=True, default=dict)),
                ('supports_remote_proposal_sync', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FacilityAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('account_data', models.JSONField(blank=True, default=dict)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sync_status', models.CharField(choices=[('not_synced', 'Not synced'), ('ok', 'OK'), ('error', 'Error')], db_index=True, default='not_synced', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_accounts_created', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='custom_code.facility')),
            ],
            options={
                'ordering': ('facility__name', 'label'),
            },
        ),
        migrations.CreateModel(
            name='FacilityAccountMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='owner', max_length=16)),
                ('can_view_credentials', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='custom_code.facilityaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facility_account_memberships_created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_account_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('account', 'user')},
            },
        ),
        migrations.AddField(
            model_name='facilityaccount',
            name='users',
            field=models.ManyToManyField(related_name='shared_facility_accounts', through='custom_code.FacilityAccountMembership', through_fields=('account', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FacilityProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('remote_payload', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='custom_code.facilityaccount')),
            ],
            options={
                'ordering': ('account__facility__name', 'title', 'external_id'),
            },
        ),
        migrations.CreateModel(
            name='FacilityProposalMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('user', 'User')], default='user', max_length=16)),
                ('can_submit_observations', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facility_proposal_memberships_created', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='custom_code.facilityproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_proposal_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('proposal', 'user')},
            },
        ),
        migrations.AddField(
            model_name='facilityproposal',
            name='users',
            field=models.ManyToManyField(related_name='shared_facility_proposals', through='custom_code.FacilityProposalMembership', through_fields=('proposal', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='facilityaccount',
            unique_together={('facility', 'label')},
        ),
        migrations.AlterUniqueTogether(
            name='facilityproposal',
            unique_together={('account', 'external_id')},
        ),
    ]
