# Generated by Django 5.2.12 on 2026-03-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0006_targetaliasinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetaliasinfo',
            name='source_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
