# Generated by Django 5.2.12 on 2026-04-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_code', '0007_targetaliasinfo_source_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitEphemeris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, default='', max_length=100)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('planet_name', models.CharField(blank=True, default='', max_length=100)),
                ('host_name', models.CharField(blank=True, default='', max_length=100)),
                ('priority', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('current_oc_min', models.FloatField(blank=True, null=True)),
                ('t0_bjd_tdb', models.FloatField(blank=True, null=True)),
                ('t0_unc', models.FloatField(blank=True, null=True)),
                ('period_days', models.FloatField(blank=True, null=True)),
                ('period_unc', models.FloatField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('depth_r_mmag', models.FloatField(blank=True, null=True)),
                ('v_mag', models.FloatField(blank=True, null=True)),
                ('r_mag', models.FloatField(blank=True, null=True)),
                ('gaia_g_mag', models.FloatField(blank=True, null=True)),
                ('min_telescope_inches', models.FloatField(blank=True, null=True)),
                ('total_observations', models.PositiveIntegerField(blank=True, null=True)),
                ('recent_observations', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('target', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='transit_ephemeris', to='custom_code.bhtomtarget')),
            ],
            options={
                'verbose_name': 'transit ephemeris',
                'verbose_name_plural': 'transit ephemerides',
            },
        ),
    ]
